licenses(["notice"])

package(default_visibility = ["//isekai:__subpackages__"])

cc_library(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@com_google_glog//:glog",
        "@omnetpp",
    ],
    alwayslink = 1,
)
