package(default_visibility = ["//visibility:public"])

licenses(["unencumbered"])

exports_files(["LICENSE"])

filegroup(
    name = "kokoro_files",
    srcs = glob(["kokoro/**"]),
    tags = ["ignore_srcs"],
    visibility = ["//visibility:private"],
)
